name: Install Samba Server

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  setup-samba:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Checks out the code from the repository

      - name: Update package list
        run: sudo apt-get update

      - name: Install Samba
        run: sudo apt-get install -y samba

      - name: Configure Samba
        run: |
          # Create a shared directory
          sudo mkdir -p /srv/samba/share
          sudo chmod 777 /srv/samba/share

          # Add a new configuration to the Samba config file
          echo "[share]" | sudo tee -a /etc/samba/smb.conf
          echo "   path = /srv/samba/share" | sudo tee -a /etc/samba/smb.conf
          echo "   read only = no" | sudo tee -a /etc/samba/smb.conf
          echo "   browsable = yes" | sudo tee -a /etc/samba/smb.conf

      - name: Start Samba Service
        run: |
          sudo service smbd restart
          sudo service nmbd restart

      - name: Test Samba Setup
        run: smbclient -L localhost -N
